apiVersion: apps/v1
kind: Deployment
metadata:
  name: daggerlab
  namespace: daggerlab
  labels:
    app: daggerlab
spec:
  selector:
    matchLabels:
      app: daggerlab
  template:
    metadata:
      labels:
        app: daggerlab
    spec:
      containers:
      - name: daggerlab
        image: node:25-alpine
        workingDir: /app
        command: [ "sh", "-c" ]
        args:
            - |
              apk add --no-cache git && \
              git clone https://github.com/freyjabun/daggerlab.git . && \
              npm install && \
              npm run dev -- --host 0.0.0.0
        ports:
        - containerPort: 5173
          name: viteendpoint
        env:
        - name: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
          value: ".simonlk.dk"
