apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: daggerlab-ingress
  namespace: daggerlab
spec:
  rules:
  - host: daggerlab.simonlk.dk
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: daggerlab-service
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - daggerlab.simonlk.dk
    secretName: daggerlab-cert # < cert-manager will store the created certificate in this secret.